# Generated by Django 4.2.7 on 2023-12-03 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20200903_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AddField(
            model_name='news',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='news',
            name='shared_by',
            field=models.ManyToManyField(blank=True, related_name='shared_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
